### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by gwilymgj** [gergo85/oc-user-plus#2]
Hithere - very keen to use your plugin! When I install it all looks good, it finds it and goes throght the install but then there is no sign of the plugin in the backend or plugin list.

Not sure where it is failing in install any idea where I could look?

**Comment by gergo85** [comment]
Have you tried to reinstall the plugin?

**Comment by vojtasvoboda** [comment]
I sent PR #4 fixing uninstalling plugin.

**Comment by gwilymgj** [comment]
Related to the uninstall problem above:

![user](https://cloud.githubusercontent.com/assets/1432243/10592646/d66430ae-7719-11e5-9dc9-27953ed48f2f.png)

**Comment by gergo85** [comment]
I fixed this issue. Thank you for reporting the bug!
