### ISSUE TITLE
Removing plugin

### ISSUE THREAD

**Issue by hfelix** [gergo85/oc-user-plus#7]
Hello,
When I try to remove the plugin I get:

"exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'iu_telephone'; check that column/key exists' in /(...)/public/vendor/laravel/framework/src/Illuminate/Database/Connection.php:390"

Can I do anything related to this?

Regards,

**Comment by gergo85** [comment]
I uninstalled the plugin without error.
Is there the iu_telephone column in your users table?

**Comment by hfelix** [comment]
There wasn't any iu_telephone. This happened after I uninstalled some plugins.
I created the fields on users database that you described on Details - New fields. Then, I was able to uninstall the plugin.

Thank you for your tip.
